config/routes.rb
Rails.application.routes.draw do

 get '/reservations/:id/braintree/new' => "braintree#new", as: "braintree_new"
 post '/reservations/:id/braintree/checkout' => "braintree#checkout", as: "braintree_checkout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#show"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings do
  	resources :reservations, only: [:create]
  end

  get "/searchresult" => "listings#searchresult"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user

	mount_uploader :image, ImageUploader
	has_many :reservations
	has_many :booked_users, through: :reservations, source: :user


	
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	
	belongs_to :listing
  	belongs_to :user

  	validate :date_available, on: :create

  	def total_price
  		x = (self.date_out - self.date_in).to_i
  		y = self.listing.price
  		x * y
  	end



private
    def date_available
   self.listing.reservations.each {|r|
       a = (r.date_in..r.date_out).to_a
       # x.pop #<= this doesn't work when user book only 1 night
       # x.shift #<= this doesn't work when user book only 1 night
       b = (date_in..date_out).to_a
       unless (a & b).empty?
         errors.add(:overlap ,"Date overlap")
         break
     end
   }
    end
end

app/models/user.rb
#class User < ApplicationRecord
 # include Clearance::User

#end

class User < ApplicationRecord
	include Clearance::User
 has_many :authentications, dependent: :destroy
 has_many :reservations
 has_many :listings
 has_many :booked_listings, through: :reservations, source: :listing

 def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     #name: auth_hash["name"],
     email: auth_hash["extra"]["raw_info"]["email"],
     password: SecureRandom.hex(10)
   )
   user.authentications << authentication
   return user
 end

 # grab fb_token to access Facebook for user data
 def fb_token
   x = self.authentications.find_by(provider: 'facebook')
   return x.token unless x.nil?
 end
 has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController

def new
  @client_token = Braintree::ClientToken.generate
  @reservation = Reservation.find(params[:id])
end

  def checkout
  @reservation = Reservation.find(params[:id])
  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  result = Braintree::Transaction.sale(
   :amount => @reservation.total_price, #this is currently hardcoded
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

  if result.success?
    redirect_to :root, :flash => { :success => "Transaction successful!" }
  else
    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
  end
end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
before_action :check_user, except:[:show, :searchresult]
before_action :check_admin, except:[:show, :searchresult]

	def index
		@listings = current_user.listings
		@listings = current_user.listings.paginate(:page => params[:page], per_page: 4)
	end

	def show
		@listing = Listing.find(params[:id])
	end

	def new
		@listing = Listing.new
	end

	def create
		@listing = current_user.listings.new(allowed_params)
		@listing.save 
		redirect_to listings_path
	end

	def edit
		@listing = Listing.find(params[:id])
	end

	def update
		@listing = Listing.find(params[:id])
		@listing.update_attributes(allowed_params)
		redirect_to listings_path

	end

	def destroy 
		@listing = Listing.find(params[:id])
		@listing.destroy
		redirect_to listings_path
	end

	def searchresult
        @listings = Listing.where('country ilike ?', "%" + params[:search] + "%")
        @listings += Listing.where('property_name ilike ?', "%" + params[:search] + "%")
        @listings.uniq!

        # SELECT * FROM listings WHERE country LIKE "%params[:searchkey]%" AND name LIKE "%params[:searchkey]%"
    end

	private
	def allowed_params

		params.require(:listing).permit(:property_name, :room_type, :total_guest, :country, :image, :price)

	end

	def check_user
		if signed_in?
		else
			redirect_to root_path
		end
	end

		def check_admin
		if current_user.role == 'admin'
		else
			redirect_to root_path
		end
	end


end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :check_user
  def index
        @reservation = Reservations.all        
    end

    def create
        @reservation = Reservation.new
        @reservation = current_user.reservations.new(allowed_params)
        @reservation.listing_id = params[:listing_id]
        # NewUserEmailMailer.notify(current_user.email).deliver_now
    if @reservation.save
        redirect_to braintree_new_path(@reservation.id)
    else
        @notice = "Booking is reserved on that day" 
        flash[:alert] = @notice
        @listing = @reservation.listing
        render "listings/show"
    end

    end


    private

    def allowed_params
        params.require(:reservation).permit(:date_in, :date_out)
    end

    def check_user
        if
            signed_in?
        else
            @notice = "Please sign in before make reservation"
            redirect_to sign_in_path, :alert => @notice
        end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
def create_from_omniauth
  auth_hash = request.env["omniauth.auth"]
  authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

  # if: previously already logged in with OAuth
  if authentication.user
    user = authentication.user
    authentication.update_token(auth_hash)
    @next = root_url
    @notice = "Signed in!"
  # else: user logs in with OAuth for the first time
  else
    user = User.create_with_auth_and_hash(authentication, auth_hash)
    # you are expected to have a path that leads to a page for editing user details
    @next = users_path(user)
    @notice = "User created. Please confirm or edit details"
  end

  sign_in(user)
  redirect_to @next, :notice => @notice
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def show
  	@listings = Listing.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/braintree/new.html.erb
<h1>Braintree#new</h1>
<p>Find me in app/views/braintree/new.html.erb</p>

<div class="demo-frame">


    Check in Date: <%= @reservation.date_in %> <br />
    Check out Date: <%= @reservation.date_out %> <br />
    Total amount: <%= "%.2f" % @reservation.total_price %>
  <%= form_for :checkout_form, html: { id: "cardForm"}, url: braintree_checkout_path(@reservation) do |form| %>


    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>
  <% end %>
</div>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>

var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pairbnb</title>

<nav class="navbar navbar-light">
     <form class="form-inline" action="/searchresult" method="get">
       <input class="form-control mr-sm-2" type="search" placeholder="Search Country or Name" aria-label="Search" name="search">
         <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
     </form>
   </nav>


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
  <%= image_tag("logo/logo.png", width: '100px') %>
     <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>
    </header>

    <section>
       <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
    </section>
  </body>
</html>

app/views/listings/edit.html.erb
<%= form_for @listing, :html => {:multipart => true} do |f| %>

	<%= f.label "Property Name" %> <br />
	<%= f.text_field :property_name %> <br />
	<%= f.label "Room Type" %> <br />
	<%= f.text_field :room_type %> <br />
	<%= f.label "Total Guest"%> <br />
	<%= f.text_field :total_guest %> <br />
	<%= f.label "Country" %> <br />
	<%= f.text_field :country %> <br />
	 <%= f.label "Price" %> <br />
	 <%= f.text_field :price %> <br />

	<%= f.label "Listing's images" %>
	<%= f.file_field :image %>
	<br />


	<%= f.submit 'CHANGE' %>

	<% end %>

app/views/listings/index.html.erb
<h1> Index - All Listing </h1>
<%= link_to 'Add Listing', new_listing_path %>

<% @listings.each do |list| %>
<p>
	
	Property Name:<%= list.property_name %> <br />
	Room Type:<%= list.room_type %> <br />
	Total Guest:<%= list.total_guest %> <br />
	Country:<%= list.country %> <br /> 
	<%= link_to 'Edit', edit_listing_path(list)%> <br />
	<%= link_to 'Delete', list, method: :delete %>
	<%= link_to 'Show', listing_path(list)%> <br />
	</p>
	
<% end %>

<%= will_paginate @listings %>

app/views/listings/new.html.erb
<h1> New Listing </h1>

<%= form_for @listing do |f| %>

	<%= f.label "Property Name" %> <br />
	 <%= f.text_field :property_name %> <br />
	<%= f.label "Room Type" %> <br />
	 <%= f.text_field :room_type %> <br />
	<%= f.label "Total Guest"%> <br />
	 <%= f.text_field :total_guest %> <br />
	<%= f.label "Country" %> <br />
	 <%= f.text_field :country %> <br />
	<%= f.label "Listing's images" %>  <br />
	 <%= f.file_field :image %> <br />
	 <%= f.label "Price" %> <br />
	 <%= f.file_field :price %>
	<br /> <br/>




	<%= f.submit 'CREATE' %>

	<% end %>

app/views/listings/searchresult.html.erb
<h1> search result </h1>

<% @listings.each do |list| %>




<p>
	
	Property Name:<%= list.property_name %> <br />
	Room Type:<%= list.room_type %> <br />
	Total Guest:<%= list.total_guest %> <br />
	Country:<%= list.country %> <br /> 
	<%= link_to 'Edit', edit_listing_path(list)%> <br />
	<%= link_to 'Delete', list, method: :delete %>
	<%= link_to 'Show', listing_path(list)%> <br />
	</p>
	
<% end %>

app/views/listings/show.html.erb
<!DOCTYPE html>
<html>
<head>
<title> Pairbnb </title>
</head>

<h1> Welcome </h1>

<body>



<% if @listing.image.url %>
 <%= image_tag @listing.image.url %>
 <% else %> 
================== <br />
NO PICTURE DISPLAY <br /> 
================== <br /> 
<% end %>
<br />




	Property Name:<%= @listing.property_name %> <br />
	Room Type:<%= @listing.room_type %> <br />
	Total Guest:<%= @listing.total_guest %> <br />
	Country:<%= @listing.country %> <br /> 
  Price:<%= @listing.price %> <br />
	<%= link_to 'Edit', edit_listing_path(@listing)%> <br />
	<%= link_to 'Delete', @listing, method: :delete %>
	<br />


       <!-- it is work -->
     <%= form_for [@listing, Reservation.new] do |f| %>
          <div class="booking-section1">
              <div class="booking-section2" >
                  <div class="booking-section3">
                      <div class="booking-section3-content" style="position: relative;">
                       <div>
                           <label>Check-in Date</label>
                          </div>
                         <!-- <input type="text" name="" id="datetimepicker6"> -->
                         <%= f.date_field :date_in, type: 'text', :id => "datetimepicker6", :placeholder => "YYYY-MM-DD", :required => true %>
                      </div>

                      <div class="booking-section3-content" style="position: relative;">
                       <div>
                          <label>Check-out Date</label>    
                         </div>
                         <!-- <input type="text" name="" id="datetimepicker7" > -->
                         <%= f.date_field :date_out, type: 'text', :id => "datetimepicker7", :placeholder => "YYYY-MM-DD", :required => true %>
                      </div>
                          <%= f.submit "Book Now", :data => { :confirm => "Are you sure ?"}, :class => "btn btn-outline-danger" %>
                          <%#= link_to "Make Payment", braintree_new_path %>
                  </div>
              </div>
          </div>

     <% end %>

       <script type="text/javascript">
   $(function () {
     $('#datetimepicker6').datetimepicker({
       format: "YYYY-MM-DD", useCurrent: true});
     $('#datetimepicker7').datetimepicker({
       format: "YYYY-MM-DD", useCurrent: false}); //Important! See issue #1075
     $("#datetimepicker6").on("dp.change", function (e) {
       $('#datetimepicker7').data("DateTimePicker").minDate(e.date);});
     $("#datetimepicker7").on("dp.change", function (e) {
       $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);});
   });
 </script>

</body>
</html>

	

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/welcome/show.html.erb
<h1> Welcome to Pairbnb </h1>


<%= link_to "Sign in with Facebook", "/auth/facebook" %>
<br /> 

<% @listings.sample(6).each do |list| %>
	<p>
	Property Name:<%= list.property_name %> <br />
	Room Type:<%= list.room_type %> <br />
	Total Guest:<%= list.total_guest %> <br />
	Country:<%= list.country %> <br /> 
	</p>
<% end %>

<%#= will_paginate @listings %>